#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width 3 
bspc config window_gap 30
bspc config top_padding 35 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config border_radius 14

picom &
nitrogen --restore

sh ~/.config/lemonbar/start.sh | lemonbar -p -B#99575656 -F#ffffff -f "Lucida Grande:style=Bold:size=14" -f "Hack Nerd Font:style=Regular:size=14" &
